Repository netlify/netlify-toml-rs, pull requests merged in 2021-03, with the labels that each got.

#15 chore: Set CODEOWNERS to runtime
  .github/CODEOWNERS
Labels: type: chore

#17 chore: add fossa license scanning
  .github/workflows/fossa.yml
Labels: type: feature

#18 feat: Add proper CI with auto-publish
  .circleci/config.yml
  .github/workflows/pr-conventions.yml
  .github/workflows/release-please.yml
  .github/workflows/renovate.yml
  .github/workflows/rust.yml
  renovate.json
  rust-toolchain
Labels: type: feature

#19 feat: Parse decoupled edge handlers
  Cargo.toml
  src/lib.rs
  tests/integration_test.rs
Labels: type: feature

#22 chore: Derive more useful traits, remove superfluous annotations
  src/lib.rs
Labels: type: chore

#20 chore: release 0.4.0
  CHANGELOG.md
  Cargo.toml
Labels: autorelease: pending, type: chore

#23 feat: Trigger release-please
  src/lib.rs
Labels: type: feature

#24 chore: release 0.5.0
  CHANGELOG.md
  Cargo.toml
Labels: autorelease: pending

#25 feat: Continue allowing parsing old-style edge handlers
  src/lib.rs
  tests/integration_test.rs
Labels: type: feature

#26 chore: release 0.6.0
  CHANGELOG.md
  Cargo.toml
Labels: autorelease: pending, type: chore

#28 chore: Delete custom renovate runner
  .github/workflows/renovate.yml
Labels: type: chore
