Repository netlify/netlify-toml-rs, pull requests merged in 2021-11, with the labels that each got.

#31 fix!: Top-level functions property is an object
  src/lib.rs
  tests/integration_test.rs
Labels: type: bug

#33 chore: release 1.0.0
  CHANGELOG.md
  Cargo.toml
Labels: type: chore, autorelease: pending

#32 chore: Add kodiak config
  .github/.kodiak.toml
Labels: type: chore, automerge
